## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:175%; text-align:center; border-radius:10px 10px;">NumPy Exercises</p>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE

import numpy as np

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
# YOUR CODE IS HERE

my_list = [5, 10, 15, 20, 25]

np.array(my_list)

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [3]:
# YOUR CODE IS HERE

np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [4]:
# YOUR CODE IS HERE

np.ones((4, 4), dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [5]:
# YOUR CODE IS HERE

np.ones((4, 4), dtype='int')*7

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [6]:
# YOUR CODE IS HERE

np.full((4, 4), 7, dtype='int')

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [7]:
# YOUR CODE IS HERE

np.arange(2, 17, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [8]:
# YOUR CODE IS HERE

np.arange(0, 25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [9]:
# YOUR CODE IS HERE

np.linspace(0, 24, 25, dtype='int').reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [10]:
# YOUR CODE IS HERE

np.linspace(0, 25, 25, dtype='int', endpoint=False).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 10. Create randomly 5 numbers with numpy.

In [11]:
# YOUR CODE IS HERE

np.random.rand(5)

array([0.78858056, 0.91984942, 0.69696293, 0.5606308 , 0.65560463])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [12]:
# YOUR CODE IS HERE

np.random.randn(5, 5)

array([[-0.26591741,  1.60461543, -2.11816452,  0.34513151, -1.51831312],
       [-0.61971528,  0.32794398, -0.71897667, -0.45654288,  0.14831265],
       [-0.06669814, -0.09438334, -4.10002752, -0.07859093,  1.88638701],
       [ 0.59351609,  1.8295077 ,  0.27277416, -0.91677355,  0.72348628],
       [-2.08000025, -0.42543399, -1.95015804,  0.16664902, -0.32990806]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [13]:
# YOUR CODE IS HERE

np.random.randint(20, 50, size=(3, 4))

array([[32, 26, 37, 27],
       [29, 32, 32, 38],
       [33, 34, 35, 49]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [14]:
# YOUR CODE IS HERE

ranarr = np.random.randint(0, 60, 48)
ranarr

array([25,  5,  9,  5, 57, 10, 25,  3, 12, 10, 45, 57, 48, 34, 49, 51,  2,
       50, 11, 43, 43, 23, 15, 22, 28, 30, 53, 42, 43, 59, 37, 26, 21, 15,
       33, 48,  1, 29, 54, 56,  5, 15, 38,  3, 52, 27, 25, 31])

In [15]:
# YOUR CODE IS HERE

ranarr.reshape(6, 8)

array([[25,  5,  9,  5, 57, 10, 25,  3],
       [12, 10, 45, 57, 48, 34, 49, 51],
       [ 2, 50, 11, 43, 43, 23, 15, 22],
       [28, 30, 53, 42, 43, 59, 37, 26],
       [21, 15, 33, 48,  1, 29, 54, 56],
       [ 5, 15, 38,  3, 52, 27, 25, 31]])

In [16]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(-1, 8)

array([[25,  5,  9,  5, 57, 10, 25,  3],
       [12, 10, 45, 57, 48, 34, 49, 51],
       [ 2, 50, 11, 43, 43, 23, 15, 22],
       [28, 30, 53, 42, 43, 59, 37, 26],
       [21, 15, 33, 48,  1, 29, 54, 56],
       [ 5, 15, 38,  3, 52, 27, 25, 31]])

In [17]:
# YOUR CODE IS HERE (RESHAPING WITH -1)

ranarr.reshape(6, -1)

array([[25,  5,  9,  5, 57, 10, 25,  3],
       [12, 10, 45, 57, 48, 34, 49, 51],
       [ 2, 50, 11, 43, 43, 23, 15, 22],
       [28, 30, 53, 42, 43, 59, 37, 26],
       [21, 15, 33, 48,  1, 29, 54, 56],
       [ 5, 15, 38,  3, 52, 27, 25, 31]])

The -1 stands for "unknown dimension" which can be inferred from another dimension. -1 corresponds to the unknown count of the row or column. It simply means that you are not sure about what number of rows or columns you can give and you are asking numpy to suggest a number of column or rows to get reshaped in. [Stackoverflow discussion on What does -1 mean in numpy reshape?](https://stackoverflow.com/questions/18691084/what-does-1-mean-in-numpy-reshape)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Indexing and Selection</p>

### Create an array named "mat" in accordance with the desired output below.

In [18]:
# YOUR CODE IS HERE 

mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [19]:
# YOUR CODE IS HERE 

mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [20]:
# YOUR CODE IS HERE 

mat[:, 0]

array([ 1,  5,  9, 13])

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:175%; text-align:center; border-radius:10px 10px;">Special Note</p>

In [21]:
# This results in a 1-d array in which rows and columns are excerpted from mat

mat[:, 0]

array([ 1,  5,  9, 13])

In [22]:
# But this results in a 2-d array

mat[:, 0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

This follows standard Python conventions and Numpy is just following that convention, but at a higher dimension. When you access an array using a single element instead of a slice, it will collapse that dimension. If you want to keep that second dimension, you need to access that dimension using a slice. [numpy array slicing, why sometimes 2-d array and sometimes 1-d array](https://stackoverflow.com/questions/19214516/numpy-array-slicing-why-sometimes-2-d-array-and-sometimes-1-d-array)

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [23]:
# YOUR CODE IS HERE 

mat[1, ::2]

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [24]:
# YOUR CODE IS HERE 

mat[:, 2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

We can assign new values to an element of a NumPy array using the **``=``** operator, just like regular python lists.

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [25]:
# YOUR CODE IS HERE 

mat[[1, 3], [0, 2]]

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [26]:
# YOUR CODE IS HERE 

mat[1::2, 0::2]

array([[ 5, 77],
       [13, 77]])

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Operations</p>

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat" with each other, rather than total sum.

In [27]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [28]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10]

array([1, 2, 4, 5, 6, 8, 9])

In [29]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat>12]

array([77, 77, 77, 13, 14, 77, 16])

In [30]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 

mat[mat<10] + mat[mat>12]

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [31]:
# YOUR CODE IS HERE 

(mat[mat<10] + mat[mat>12]).std()

29.700546274093877

### 22. Get the sum of the 2nd column (index number 1) in the original "mat".

In [32]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [33]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat[:, 2] = [3, 7, 11, 15]
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
# YOUR CODE IS HERE 

mat[:, 1].sum(axis=0)

32

### 23. Get the median, mean and std of 3rd column (index number 2) in "mat".

In [35]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 

a = mat[:, 2:3]
a

array([[ 3],
       [ 7],
       [11],
       [15]])

In [37]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

b = mat[2]
b

array([ 9, 10, 11, 12])

In [38]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 

print(np.median(a))
print(np.median(b))

9.0
10.5


In [39]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

print(np.mean(a))
print(np.mean(b))

9.0
10.5


In [40]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 

print(np.std(a))
print(np.std(b))

4.47213595499958
1.118033988749895
